# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beta-design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 791)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(70, 30, 961, 711))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 461, 631))
        self.label.setStyleSheet("border-image: url(:/images/friendly-chatbot.jpg);\n"
"border-top-left-radius: 50px;\n"
"border-bottom-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(470, 30, 441, 631))
        self.label_2.setStyleSheet("background-color:rgb(52, 79, 161);\n"
"border-bottom-right-radius: 50px;\n"
"border-top-right-radius: 50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(580, 120, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(27)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(590, 550, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"   background-color:qlineargradient(spread:pad,x1:0.505682, x2:1, y2:0.477,stop:0 rgb(255,140,71),stop:1 rgb(255,201,71));\n"
"   color:rgba(255, 255, 255, 210);\n"
"   border-radius:5px;\n"
"   border-top-right-radius: 15px;\n"
"   border-bottom-right-radius: 15px;\n"
"   border-top-left-radius: 15px;\n"
"   border-bottom-left-radius: 15px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"   background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477,stop:0 rgb(250,136,0),stop:1 rgb(250,94,0));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   background-color:rgb(200,108,0);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(60, 590, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 50, 25, 25))
        self.pushButton_3.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_3.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("entypo")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"   background-color: rgba(0, 0, 0, 0);\n"
"   color:rgb(255,255,255);\n"
"   font:bold;\n"
"   font-size:20px;\n"
"   font-family:entypo;\n"
"}\n"
"QPushButton:hover{\n"
"   color:rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"   padding-top:5px;\n"
"   padding-left:5px;\n"
"   color:rgb(91, 88, 53);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(520, 190, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(570, 180, 241, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(490, 260, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(490, 300, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(510, 330, 681, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(510, 360, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(490, 400, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(510, 430, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(490, 470, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_12.setObjectName("label_12")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(490, 280, 171, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Terrobyte"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.label_4.setText(_translate("Form", "Created By: Team Invincible"))
        self.pushButton_3.setText(_translate("Form", "X"))
        self.label_5.setText(_translate("Form", "An Interactive Assistant for you !!"))
        self.label_6.setText(_translate("Form", "Main Features:"))
        self.label_7.setText(_translate("Form", "1. Check for Availability of Vaccine for your Pincode"))
        self.label_8.setText(_translate("Form", "and respond you vebal way as well as textual way"))
        self.label_10.setText(_translate("Form", "by sending message to telegram channel"))
        self.label_9.setText(_translate("Form", "2. Record Your Oxygen Level and store the data"))
        self.label_11.setText(_translate("Form", " in the form of .csv file."))
        self.label_12.setText(_translate("Form", "3. Trivia Game with feature of random Question"))

